# Generated by Django 4.0.3 on 2023-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='final_captain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Captain'),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_chamber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chamber'),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_shiptype',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ship Type'),
        ),
    ]
