# Generated by Django 4.2.7 on 2023-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_deed_validation_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed_uri', models.URLField(unique=True)),
                ('deed_date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('captain', models.CharField(blank=True, max_length=255, null=True)),
                ('chamber', models.CharField(blank=True, max_length=255, null=True)),
                ('shiptype', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sailor_uri', models.URLField(blank=True, null=True)),
                ('location_uri', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
