# Generated by Django 4.2.7 on 2023-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_validateddeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='creditor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='creditor_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='debt_amount',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='deed',
            name='debt_amount_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_creditor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Creditor Name'),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_debt_amount',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Debt Amount'),
        ),
        migrations.AddField(
            model_name='deed',
            name='final_debt_amount_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='Debt Amount (Integer)'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='deed_uri',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
