# Generated by Django 4.2.7 on 2023-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_deed_final_captain_deed_final_chamber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='validation_complete',
            field=models.BooleanField(default=False),
        ),
    ]
