from django.db import models

class Deed(models.Model):
    deed_uri = models.URLField(unique=True)
    deed_date = models.DateField()
    final_name = models.CharField(max_length=200, blank=True, verbose_name='Name')
    final_location = models.CharField(max_length=200, blank=True, verbose_name='Location')
    final_ship_name = models.CharField(max_length=200, blank=True, verbose_name='Ship')
    final_role = models.CharField(max_length=200, blank=True, verbose_name='Role')
    final_organization = models.CharField(max_length=200, blank=True, verbose_name='Organization')
    final_captain = models.CharField(max_length=200, blank=True, null=True, verbose_name='Captain')
    final_chamber = models.CharField(max_length=200, blank=True, null=True, verbose_name='Chamber')
    final_shiptype = models.CharField(max_length=200, blank=True, null=True, verbose_name='Ship Type')
    final_remarks = models.TextField(blank=True, null=True, verbose_name='Remarks')
    suggested_name = models.CharField(max_length=200, blank=True)
    suggested_location = models.CharField(max_length=200, blank=True)
    suggested_role = models.CharField(max_length=200, blank=True)
    suggested_organization = models.CharField(max_length=200, blank=True)
    suggested_ship_name = models.CharField(max_length=200, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    role = models.CharField(max_length=255, blank=True, null=True)
    organization = models.CharField(max_length=255, blank=True, null=True)
    ship_name = models.CharField(max_length=255, blank=True, null=True)
    location_htr = models.CharField(max_length=255, blank=True, null=True)
    role_htr = models.CharField(max_length=255, blank=True, null=True)
    organization_htr = models.CharField(max_length=255, blank=True, null=True)
    ship_name_htr = models.CharField(max_length=255, blank=True, null=True)
    sailor_uri = models.URLField(blank=True, null=True)
    location_uri = models.URLField(blank=True, null=True)
    interesting_text = models.TextField(blank=True, null=True)
    interesting_text_after = models.TextField(blank=True, null=True)
    possible_names = models.TextField(blank=True, null=True)
    possible_locations = models.TextField(blank=True, null=True)
    subject = models.TextField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    full_coords = models.TextField(blank=True, null=True)
    dimensions = models.TextField(blank=True, null=True)
    image_url = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.deed_uri} - {self.deed_date}"
